class CountryCode {
  final String code;
  final String flag;
  final String name;

  const CountryCode({
    required this.code,
    required this.flag,
    required this.name,
  });
}

const List<CountryCode> countryCodes = [
  CountryCode(code: '+93', flag: '🇦🇫', name: 'Afghanistan'),
  CountryCode(code: '+355', flag: '🇦🇱', name: 'Albania'),
  CountryCode(code: '+213', flag: '🇩🇿', name: 'Algeria'),
  CountryCode(code: '+376', flag: '🇦🇩', name: 'Andorra'),
  CountryCode(code: '+244', flag: '🇦🇴', name: 'Angola'),
  CountryCode(code: '+54', flag: '🇦🇷', name: 'Argentina'),
  CountryCode(code: '+374', flag: '🇦🇲', name: 'Armenia'),
  CountryCode(code: '+61', flag: '🇦🇺', name: 'Australia'),
  CountryCode(code: '+43', flag: '🇦🇹', name: 'Austria'),
  CountryCode(code: '+994', flag: '🇦🇿', name: 'Azerbaijan'),
  CountryCode(code: '+973', flag: '🇧🇭', name: 'Bahrain'),
  CountryCode(code: '+880', flag: '🇧🇩', name: 'Bangladesh'),
  CountryCode(code: '+375', flag: '🇧🇾', name: 'Belarus'),
  CountryCode(code: '+32', flag: '🇧🇪', name: 'Belgium'),
  CountryCode(code: '+501', flag: '🇧🇿', name: 'Belize'),
  CountryCode(code: '+229', flag: '🇧🇯', name: 'Benin'),
  CountryCode(code: '+975', flag: '🇧🇹', name: 'Bhutan'),
  CountryCode(code: '+591', flag: '🇧🇴', name: 'Bolivia'),
  CountryCode(code: '+387', flag: '🇧🇦', name: 'Bosnia'),
  CountryCode(code: '+267', flag: '🇧🇼', name: 'Botswana'),
  CountryCode(code: '+55', flag: '🇧🇷', name: 'Brazil'),
  CountryCode(code: '+673', flag: '🇧🇳', name: 'Brunei'),
  CountryCode(code: '+359', flag: '🇧🇬', name: 'Bulgaria'),
  CountryCode(code: '+855', flag: '🇰🇭', name: 'Cambodia'),
  CountryCode(code: '+237', flag: '🇨🇲', name: 'Cameroon'),
  CountryCode(code: '+1', flag: '🇨🇦', name: 'Canada'),
  CountryCode(code: '+56', flag: '🇨🇱', name: 'Chile'),
  CountryCode(code: '+86', flag: '🇨🇳', name: 'China'),
  CountryCode(code: '+57', flag: '🇨🇴', name: 'Colombia'),
  CountryCode(code: '+506', flag: '🇨🇷', name: 'Costa Rica'),
  CountryCode(code: '+385', flag: '🇭🇷', name: 'Croatia'),
  CountryCode(code: '+53', flag: '🇨🇺', name: 'Cuba'),
  CountryCode(code: '+357', flag: '🇨🇾', name: 'Cyprus'),
  CountryCode(code: '+420', flag: '🇨🇿', name: 'Czech Republic'),
  CountryCode(code: '+45', flag: '🇩🇰', name: 'Denmark'),
  CountryCode(code: '+593', flag: '🇪🇨', name: 'Ecuador'),
  CountryCode(code: '+20', flag: '🇪🇬', name: 'Egypt'),
  CountryCode(code: '+503', flag: '🇸🇻', name: 'El Salvador'),
  CountryCode(code: '+372', flag: '🇪🇪', name: 'Estonia'),
  CountryCode(code: '+251', flag: '🇪🇹', name: 'Ethiopia'),
  CountryCode(code: '+679', flag: '🇫🇯', name: 'Fiji'),
  CountryCode(code: '+358', flag: '🇫🇮', name: 'Finland'),
  CountryCode(code: '+33', flag: '🇫🇷', name: 'France'),
  CountryCode(code: '+995', flag: '🇬🇪', name: 'Georgia'),
  CountryCode(code: '+49', flag: '🇩🇪', name: 'Germany'),
  CountryCode(code: '+233', flag: '🇬🇭', name: 'Ghana'),
  CountryCode(code: '+30', flag: '🇬🇷', name: 'Greece'),
  CountryCode(code: '+502', flag: '🇬🇹', name: 'Guatemala'),
  CountryCode(code: '+504', flag: '🇭🇳', name: 'Honduras'),
  CountryCode(code: '+852', flag: '🇭🇰', name: 'Hong Kong'),
  CountryCode(code: '+36', flag: '🇭🇺', name: 'Hungary'),
  CountryCode(code: '+354', flag: '🇮🇸', name: 'Iceland'),
  CountryCode(code: '+91', flag: '🇮🇳', name: 'India'),
  CountryCode(code: '+62', flag: '🇮🇩', name: 'Indonesia'),
  CountryCode(code: '+98', flag: '🇮🇷', name: 'Iran'),
  CountryCode(code: '+964', flag: '🇮🇶', name: 'Iraq'),
  CountryCode(code: '+353', flag: '🇮🇪', name: 'Ireland'),
  CountryCode(code: '+972', flag: '🇮🇱', name: 'Israel'),
  CountryCode(code: '+39', flag: '🇮🇹', name: 'Italy'),
  CountryCode(code: '+81', flag: '🇯🇵', name: 'Japan'),
  CountryCode(code: '+962', flag: '🇯🇴', name: 'Jordan'),
  CountryCode(code: '+7', flag: '🇰🇿', name: 'Kazakhstan'),
  CountryCode(code: '+254', flag: '🇰🇪', name: 'Kenya'),
  CountryCode(code: '+965', flag: '🇰🇼', name: 'Kuwait'),
  CountryCode(code: '+996', flag: '🇰🇬', name: 'Kyrgyzstan'),
  CountryCode(code: '+856', flag: '🇱🇦', name: 'Laos'),
  CountryCode(code: '+371', flag: '🇱🇻', name: 'Latvia'),
  CountryCode(code: '+961', flag: '🇱🇧', name: 'Lebanon'),
  CountryCode(code: '+218', flag: '🇱🇾', name: 'Libya'),
  CountryCode(code: '+370', flag: '🇱🇹', name: 'Lithuania'),
  CountryCode(code: '+352', flag: '🇱🇺', name: 'Luxembourg'),
  CountryCode(code: '+853', flag: '🇲🇴', name: 'Macau'),
  CountryCode(code: '+60', flag: '🇲🇾', name: 'Malaysia'),
  CountryCode(code: '+960', flag: '🇲🇻', name: 'Maldives'),
  CountryCode(code: '+356', flag: '🇲🇹', name: 'Malta'),
  CountryCode(code: '+52', flag: '🇲🇽', name: 'Mexico'),
  CountryCode(code: '+373', flag: '🇲🇩', name: 'Moldova'),
  CountryCode(code: '+377', flag: '🇲🇨', name: 'Monaco'),
  CountryCode(code: '+976', flag: '🇲🇳', name: 'Mongolia'),
  CountryCode(code: '+212', flag: '🇲🇦', name: 'Morocco'),
  CountryCode(code: '+95', flag: '🇲🇲', name: 'Myanmar'),
  CountryCode(code: '+264', flag: '🇳🇦', name: 'Namibia'),
  CountryCode(code: '+977', flag: '🇳🇵', name: 'Nepal'),
  CountryCode(code: '+31', flag: '🇳🇱', name: 'Netherlands'),
  CountryCode(code: '+64', flag: '🇳🇿', name: 'New Zealand'),
  CountryCode(code: '+505', flag: '🇳🇮', name: 'Nicaragua'),
  CountryCode(code: '+234', flag: '🇳🇬', name: 'Nigeria'),
  CountryCode(code: '+850', flag: '🇰🇵', name: 'North Korea'),
  CountryCode(code: '+47', flag: '🇳🇴', name: 'Norway'),
  CountryCode(code: '+968', flag: '🇴🇲', name: 'Oman'),
  CountryCode(code: '+92', flag: '🇵🇰', name: 'Pakistan'),
  CountryCode(code: '+507', flag: '🇵🇦', name: 'Panama'),
  CountryCode(code: '+595', flag: '🇵🇾', name: 'Paraguay'),
  CountryCode(code: '+51', flag: '🇵🇪', name: 'Peru'),
  CountryCode(code: '+63', flag: '🇵🇭', name: 'Philippines'),
  CountryCode(code: '+48', flag: '🇵🇱', name: 'Poland'),
  CountryCode(code: '+351', flag: '🇵🇹', name: 'Portugal'),
  CountryCode(code: '+974', flag: '🇶🇦', name: 'Qatar'),
  CountryCode(code: '+40', flag: '🇷🇴', name: 'Romania'),
  CountryCode(code: '+7', flag: '🇷🇺', name: 'Russia'),
  CountryCode(code: '+250', flag: '🇷🇼', name: 'Rwanda'),
  CountryCode(code: '+966', flag: '🇸🇦', name: 'Saudi Arabia'),
  CountryCode(code: '+221', flag: '🇸🇳', name: 'Senegal'),
  CountryCode(code: '+381', flag: '🇷🇸', name: 'Serbia'),
  CountryCode(code: '+65', flag: '🇸🇬', name: 'Singapore'),
  CountryCode(code: '+421', flag: '🇸🇰', name: 'Slovakia'),
  CountryCode(code: '+386', flag: '🇸🇮', name: 'Slovenia'),
  CountryCode(code: '+27', flag: '🇿🇦', name: 'South Africa'),
  CountryCode(code: '+82', flag: '🇰🇷', name: 'South Korea'),
  CountryCode(code: '+34', flag: '🇪🇸', name: 'Spain'),
  CountryCode(code: '+94', flag: '🇱🇰', name: 'Sri Lanka'),
  CountryCode(code: '+46', flag: '🇸🇪', name: 'Sweden'),
  CountryCode(code: '+41', flag: '🇨🇭', name: 'Switzerland'),
  CountryCode(code: '+886', flag: '🇹🇼', name: 'Taiwan'),
  CountryCode(code: '+992', flag: '🇹🇯', name: 'Tajikistan'),
  CountryCode(code: '+255', flag: '🇹🇿', name: 'Tanzania'),
  CountryCode(code: '+66', flag: '🇹🇭', name: 'Thailand'),
  CountryCode(code: '+90', flag: '🇹🇷', name: 'Turkey'),
  CountryCode(code: '+993', flag: '🇹🇲', name: 'Turkmenistan'),
  CountryCode(code: '+256', flag: '🇺🇬', name: 'Uganda'),
  CountryCode(code: '+380', flag: '🇺🇦', name: 'Ukraine'),
  CountryCode(code: '+971', flag: '🇦🇪', name: 'United Arab Emirates'),
  CountryCode(code: '+44', flag: '🇬🇧', name: 'United Kingdom'),
  CountryCode(code: '+1', flag: '🇺🇸', name: 'United States'),
  CountryCode(code: '+598', flag: '🇺🇾', name: 'Uruguay'),
  CountryCode(code: '+998', flag: '🇺🇿', name: 'Uzbekistan'),
  CountryCode(code: '+58', flag: '🇻🇪', name: 'Venezuela'),
  CountryCode(code: '+84', flag: '🇻🇳', name: 'Vietnam'),
  CountryCode(code: '+967', flag: '🇾🇪', name: 'Yemen'),
  CountryCode(code: '+260', flag: '🇿🇲', name: 'Zambia'),
  CountryCode(code: '+263', flag: '🇿🇼', name: 'Zimbabwe'),
];

CountryCode get defaultCountry => countryCodes.firstWhere(
  (c) => c.code == '+65',
  orElse: () => countryCodes.first,
);

CountryCode? getCountryByCode(String code) {
  try {
    return countryCodes.firstWhere((c) => c.code == code);
  } catch (e) {
    return null;
  }
}

